sonar.projectKey=DarsaniTS07_E-Commerce_Microservices
sonar.organization=darsanits07

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=E-Commerce_Microservices

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.js,**/*.spec.js,infra/**,scripts/**,.github/**
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*

# JavaScript/TypeScript
sonar.javascript.lcov.reportPaths=*/coverage/lcov.info
